import React from "react";
import { Cabin, Nunito_Sans, Poltawski_Nowy } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import Providers from "./providers/Providers";
import { Toaster } from "react-hot-toast";
import { TbTriangleFilled } from "react-icons/tb";
import { FaExclamationTriangle } from "react-icons/fa";
import Link from "next/link";

const poltawskiNowy = Poltawski_Nowy({
  subsets: ["latin"],
  variable: "--font-poltawski",
});

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  variable: "--font-nunito",
});

const cabin = Cabin({
  subsets: ["latin"],
  variable: "--font-cabin",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const GlobalNotFound = () => {
  return (
    <html lang="en">
      <body
        className={`${poltawskiNowy.variable} ${nunitoSans.variable} ${cabin.variable} antialiased flex flex-col min-h-screen`}
      >
        <Providers>
          <header>
            <nav>
              <Navbar />
            </nav>
          </header>
          <main className="container mx-auto px-4 mt-20 flex-1">
            <div className="min-h-[78vh] flex flex-col items-center justify-center">
              <div className="card bg-base-200 p-20 lg:p-24 rounded-xl shadow-md space-y-3 text-center">
                <div className="flex items-center justify-center">
                  <FaExclamationTriangle size={120} className="text-warning" />
                </div>
                <h2>Ooooops!</h2>
                <p className="text-lg">
                  The page you are looking for does not exist. It might have
                  been moved or deleted.
                </p>
                <p className="text-lg">But you can return to the homepage.</p>
                <p>
                  <Link href="/" className="btn btn-success">
                    Home
                  </Link>
                </p>
              </div>
            </div>
          </main>
          <Toaster position="bottom-center" reverseOrder={false} />
          <footer>
            <Footer />
          </footer>
        </Providers>
      </body>
    </html>
  );
};

export default GlobalNotFound;
