import { Cabin, Nunito_Sans, Poltawski_Nowy } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import Providers from "./providers/Providers";
import { Toaster } from "react-hot-toast";

const poltawskiNowy = Poltawski_Nowy({
  subsets: ["latin"],
  variable: "--font-poltawski",
});

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  variable: "--font-nunito",
});

const cabin = Cabin({
  subsets: ["latin"],
  variable: "--font-cabin",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poltawskiNowy.variable} ${nunitoSans.variable} ${cabin.variable} antialiased flex flex-col min-h-screen`}
      >
        <Providers>
          <header>
            <nav>
              <Navbar />
            </nav>
          </header>
          <main className="container mx-auto px-4 mt-20 flex-1">
            {children}
          </main>
          <Toaster position="bottom-center" reverseOrder={false} />
          <footer>
            <Footer />
          </footer>
        </Providers>
      </body>
    </html>
  );
}
